### ISSUE TITLE
Working alternative

### ISSUE THREAD

**Issue by marklagendijk** [puhastudio/node-transip-dyndns#1]
I recently created [transip-dns-cli](https://github.com/marklagendijk/node-transip-dns-cli) that works with the new TransIP API.

**Comment by yn5** [comment]
Nice, thanks for the heads up! I’m not actively using and / or maintaining this repository. What would you suggest or like me to do? Depricate this repository and link to yours?

**Comment by marklagendijk** [comment]
I think that would be good.

**Comment by yn5** [comment]
Done, sorry it took forever.
